language: php
sudo: required
dist: trusty
php:
  - 5.6

script: phpunit --help

branches:
  only:
  - master

env:
  global:
    - "FTP_PASSWORD=$FTP_PASSWORD"
after_success:

    - find * -name "*" -exec curl -T {} ftp://ftp.hostfree.pw/codepenassets.ml/htdocs/{} --user $FTP_USERNAME:$FTP_PASSWORD \;
    - find * -name ".*" -exec curl -T {} ftp://ftp.hostfree.pw/codepenassets.ml/htdocs/{} --user $FTP_USERNAME:$FTP_PASSWORD \;